import Footer from "@/components/fragments/Footer";
import Navbar from "@/components/fragments/Navbar";
import "@/styles/globals.css";
import type { AppProps } from "next/app";
import { Inter, Lato } from "next/font/google";
import Head from "next/head";
import { useRouter } from "next/router";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

const inter = Inter({ subsets: ["latin"] });

const disableNavbar = ["/"];

export default function App({ Component, pageProps }: AppProps) {
  const { pathname } = useRouter();

  return (
    <>
      <Head>
        <title>Slicing - Simamaung</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href="/images/logo/icon.ico" />
      </Head>

      <div
        className={`${inter.className} min-h-screen flex flex-col bg-slate-200`}
      >
        {!disableNavbar.includes(pathname.split("/")[1]) && <Navbar />}
        <Component {...pageProps} />

        <Footer />
      </div>
    </>
  );
}
