import Head from "next/head";
import Image from "next/image";
import NewsLayout from "@/components/layouts/NewsLayout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Slicing - Simamaung</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NewsLayout category={["Simamaung"]}>
        <div className="w-full flex items-center justify-center pt-35">
          <h1 className="text-2xl font-bold uppercase">Hallo</h1>
        </div>
      </NewsLayout>
    </>
  );
}
