import Head from "next/head";
import MainLayout from "@/components/layouts/MainLayout";
import MainView from "@/components/views";

export default function Home() {
  return (
    <>
      <Head>
        <title>Slicing - Simamaung</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href="/images/logo/icon.ico" />
      </Head>
      <MainLayout category={["Simamaung"]}>
        <MainView />
      </MainLayout>
    </>
  );
}
